#page title
page_title                                : Bookshlf                                 # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/us/app/bookshlf-scan-to-save-books/id1638251677                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/logo.png                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Bookshlf                                 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Save books with a scan.                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : An app to help you save books to read for later. No longer will you have to take a picture of the cover or remember the name. Simply scan the books barcode and add it to your Bookshelf.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Jeremy Hernandez                                
your_link                                 : https://jermhern.carrd.co                     
your_city                                 : Alexandria                                
email_address                             : jermhern@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : jermhern
github_username                           : jermhern
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Designed for simplicity
    description                           : All you have to do is find your new favorite book at your local bookstore or library, scan it with Bookshelf, and just like that, its saved for later!
    fontawesome_icon_name                 : check
    
  - title                                 : All-In-One
    description                           : Books in your Bookshelf have descriptions, ratings, links to buy online, and an option to share with others!
    fontawesome_icon_name                 : star

  - title                                 : Just one scan
    description                           : Bookshelf solves the problem of taking a photo of book cover to save it for later, only have it buried in your photos library.
    fontawesome_icon_name                 : barcode

  - title                                 : Works on any book
    description                           : If you have a new book or old, as long as you have a barcode you can save it in Bookshelf.
    fontawesome_icon_name                 : quote-left

  - title                                 : Offline Bookshelf
    description                           : Dont worry. You can always access your book scans offline if you lose connection!
    fontawesome_icon_name                 : wifi
    
  - title                                 : So much fun!
    description                           : Find out how many more books you can save for later with Bookshelf, its addicting! Download today.
    fontawesome_icon_name                 : book



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/bookshelf-header.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
